# Reference: https://github.com/i3/i3/blob/next/etc/config

## general settings
start-at-login = true
# i3 doesn't have "normalizations" feature that why we disable them here.
# But the feature is very helpful.
# Normalizations eliminate all sorts of weird tree configurations that don't make sense.
# Give normalizations a chance and enable them back.
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# See: https://nikitabobko.github.io/AeroSpace/guide#layouts
# The 'accordion-padding' specifies the size of accordion padding
# You can set 0 to disable the padding feature
accordion-padding = 30

# Possible values: tiles|accordion
default-root-container-layout = 'tiles'

# Possible values: horizontal|vertical|auto
# 'auto' means: wide monitor (anything wider than high) gets horizontal orientation,
#               tall monitor (anything higher than wide) gets vertical orientation
default-root-container-orientation = 'auto'

# Mouse follows focus when focused monitor changes
# Drop it from your config, if you don't like this behavior
# See https://nikitabobko.github.io/AeroSpace/guide#on-focus-changed-callbacks
# See https://nikitabobko.github.io/AeroSpace/commands#move-mouse
# Fallback value (if you omit the key): on-focused-monitor-changed = []
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

# You can effectively turn off macOS "Hide application" (cmd-h) feature by toggling this flag
# Useful if you don't use this macOS feature, but accidentally hit cmd-h or cmd-alt-h key
# Also see: https://nikitabobko.github.io/AeroSpace/goodness#disable-hide-app
automatically-unhide-macos-hidden-apps = false

## workspaces
[workspace-to-monitor-force-assignment]
B = '^LG'
C = '^Studio'
T = '^DELL'
M = '^DELL'
1 = '^DELL'
2 = '^DELL'
3 = '^DELL'

### termial workspace
[[on-window-detected]]
if.app-id = 'net.kovidgoyal.kitty'
run = 'move-node-to-workspace T'
[[on-window-detected]]
if.app-id = 'com.tinyspeck.slackmacgap'
run = 'move-node-to-workspace T'
[[on-window-detected]]
if.app-id = 'com.todoist.mac.Todoist'
run = 'move-node-to-workspace T'
[[on-window-detected]]
if.app-id = 'com.apple.Safari'
run = 'move-node-to-workspace T'
[[on-window-detected]]
if.app-id = 'org.mozilla.firefoxdeveloperedition'
# run = [ 'layout h_accordion', 'move-node-to-workspace B' ]
run = [ 'move-node-to-workspace B' ]

### coding workspace
[[on-window-detected]]
if.app-id = 'org.gnu.Emacs'
run = [ 'move-node-to-workspace C' ]
[[on-window-detected]]
if.app-id = 'com.microsoft.VSCode'
run = [ 'move-node-to-workspace C' ]
# run = [ 'layout h_accordion', 'move-node-to-workspace C' ]

### music workspace
[[on-window-detected]]
if.app-id = 'com.spotify.client'
run = 'move-node-to-workspace M'
[[on-window-detected]]
if.app-id = 'com.netease.163music'
run = 'move-node-to-workspace M'
[[on-window-detected]]
if.app-id = 'com.apple.podcasts'
run = 'move-node-to-workspace M'
[[on-window-detected]]
if.app-id = 'com.apple.Music'
run = 'move-node-to-workspace M'
[[on-window-detected]]
if.app-id = 'com.apple.Home'
run = 'move-node-to-workspace 1'
[[on-window-detected]]
if.app-id = 'org.pqrs.Karabiner-Elements.Settings'
run = 'move-node-to-workspace 1'
[[on-window-detected]]
if.app-id = 'com.apple.mail'
run = 'move-node-to-workspace 1'
[[on-window-detected]]
if.app-name-regex-substring = '^(dash|istat|voila|system settings|screen sharing)'
run = 'layout floating'
# [[on-window-detected]]
# check-further-callbacks = true
# run = 'move-node-to-workspace 1'

# [[on-window-detected]]
# check-further-callbacks = true
# run = 'layout floating'
