(setq key-chord-two-keys-delay 0.04) ; default 0.1
(setq key-chord-one-key-delay 0.01) ; default 0.2

(setq-default evil-escape-key-sequence "kj")
(key-chord-define-global "z0" 'delete-other-windows)
(key-chord-define-global ";q" 'spacemacs/default-pop-shell)
;; (key-chord-define-global ";g" 'evil-search-word-forward)
(key-chord-define-global ";w" 'save-buffer)
(key-chord-define-global ";c" 'dired)
(key-chord-define-global "x0" 'select-window-0)
(key-chord-define-global ";1" 'select-window-1)
(key-chord-define-global ";2" 'select-window-2)
(key-chord-define-global ";3" 'select-window-3)
(key-chord-define-global ";4" 'select-window-4)
(key-chord-define-global ";5" 'select-window-5)
(key-chord-define-global ";f" 'evil-search-forward)
(key-chord-define-global "xm" 'magit-dispatch-popup)
(key-chord-define-global "xn" 'magit-gitflow-popup)
(key-chord-define-global "e3" 'phi-replace)
;; (key-chord-define-global "m," 'mc/mark-next-like-this)
;; (key-chord-define-global "m." 'mc/mark-previous-like-this)
;; (key-chord-define-global "s1" 'ispell-region)
(key-chord-define-global ";x" 'counsel-M-x)
