#!/usr/bin/env bash

function resize
{
    while [[ "$1" ]]; do
        /usr/local/bin/yabai -m window --resize "$2":"$1"
        shift; shift
    done
}

function main
{
    case "${1:0:1}" in
        "l") resize "-20:0" "left" "-20:0" "right" ;;
        "r") resize "20:0" "left" "20:0" "right" ;;
        "d") resize "0:20" "top" "0:20" "bottom" ;;
        "u") resize "0:-20" "top" "0:-20" "bottom" ;;
    esac
}

main "$@"