#!/usr/bin/env sh

# general space settings
if [ "$(/usr/local/bin/yabai -m query --displays | /usr/local/bin/jq length)" -eq 1 ]; then
    yabai -m config layout                       stack
else
    yabai -m config layout                       bsp
fi