#!/usr/bin/env sh

# refocus on window/app closed/quit
yabai -m signal --add event=window_destroyed action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus recent || yabai -m window --focus first"
yabai -m signal --add event=application_terminated action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus recent || yabai -m window --focus first"
yabai -m signal --add event=application_activated action="~/.config/yabai/un-recent-zoom-fullscreen-if-same-space"
yabai -m signal --add event=window_focused action="bb -cp ~/.config/yabai  ~/.config/yabai/un-recent-zoom-fullscreen-if-same-space"
yabai -m signal --add event=application_front_switched action="bb -cp ~/.config/yabai ~/.config/yabai/un-recent-zoom-fullscreen-if-same-space"
yabai -m signal --add event=window_focused action="bb -cp ~/.config/yabai  ~/.config/yabai/display-app-title"
yabai -m signal --add event=window_title_changed action="bb -cp ~/.config/yabai  ~/.config/yabai/display-app-title"
yabai -m signal --add event=application_front_switched action="bb -cp ~/.config/yabai  ~/.config/yabai/display-app-title"