#!/bin/bash

set -e

notmuch=/run/current-system/sw/bin/notmuch
echo -n Filtering new messages
notmuch tag -new +inbox "folder:/Inbox/"
notmuch tag -new "tag:deleted"
notmuch tag -new "tag:new"
source ~/Dropbox/sync/notmuch-hooks/post-new
