#!/bin/bash

echo "Moving messages according to notmuch tags"

# Make sure we have updated paths
notmuch new --no-hooks

# Archive files that are NOT tagged Inbox
filter="folder:/Inbox/ tag:archived -tag:inbox"
echo "$(notmuch count $filter) archived messages"
notmuch search --output=files --format=text0 $filter | xargs -0 --no-run-if-empty mv -t "$HOME/mail/namy.19@gmail.com/[Gmail]/Archived/cur"
# notmuch search --output=files --format=text0 $filter | xargs -0 --no-run-if-empty rm

# filter="tag:deleted tag:spam tag:junk AND (folder:/company/INBOX/ OR folder:/company/Archive/ AND NOT folder:/Junk/)"
# filter="tag:trash tag:deleted tag:spam tag:junk"
filter="tag:trash tag:deleted tag:spam tag:junk -folder:/Trash/"
notmuch tag -inbox $filter
echo "$(notmuch count $filter) messages to trash"
notmuch search --output=files --format=text0 $filter | xargs -0 --no-run-if-empty mv -t "$HOME/mail/namy.19@gmail.com/[Gmail]/Trash/cur"

# Make sure we have updated paths
notmuch new --no-hooks
