#!/bin/zsh
source ~/.zshrc;


#########################
# Contants.
#########################
VPREFS="${HOME}/Library/Caches/com.runningwithcrayons.Alfred-2/Workflow Data/"
NVPREFS="${HOME}/Library/Application Support/Alfred 2/Workflow Data/"

###############################################################################
# Read the bundleid from the workflow's info.plist
###############################################################################
getBundleId() {
  /usr/libexec/PlistBuddy  -c "Print :bundleid" "info.plist"
}

###############################################################################
# Get the workflow data dir
###############################################################################
getDataDir() {
  local BUNDLEID=$(getBundleId)
  echo "${NVPREFS}${BUNDLEID}"
}

if [ ! -d "$(getDataDir)" ]; then
   mkdir -p "$(getDataDir)";
   touch "$(getDataDir)/Editor.txt";
fi

# Set the editor name.
editor=`cat "$(getDataDir)/Editor.txt"`;

"$editor/Contents/SharedSupport/bin/subl" --add "$1";
