#!/usr/bin/env bash

if [ "$#" -eq 0 ]; then
  doom sync
  # ~/local/bin/make-hotfuzz
elif [ "$1" = "sync" ] && [ -z "$2" ]; then
  doom "$@"
  # ~/local/bin/make-hotfuzz
else
  doom "$@"
fi

sh ~/Dropbox/sync/scripts/make-adguard-upstream-dns-conf.sh || true
sh ~/Dropbox/sync/scripts/cp-surge-conf.sh || true
