#!/usr/bin/env sh

# the scripting-addition must be loaded manually if
# you are running yabai on macOS Big Sur. Uncomment
# the following line to have the injection performed
# when the config is executed during startup.
#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)
#
export PATH=/run/current-system/sw/bin:$PATH

sudo yabai --load-sa || true
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

. ~/.config/yabai/rules

# global settings
yabai -m config debug_output off
# yabai -m config external_bar all:16:0
# yabai -m config mouse_follows_focus          on
yabai -m config mouse_follows_focus off
# yabai -m config focus_follows_mouse          autoraise
# yabai -m config focus_follows_mouse          autofocus
yabai -m config focus_follows_mouse off
yabai -m config window_origin_display focused
yabai -m config window_placement second_child
yabai -m config window_topmost off
yabai -m config window_shadow on
yabai -m config window_opacity off
yabai -m config active_window_opacity 1.0
yabai -m config normal_window_opacity 1.0
yabai -m config window_border on
yabai -m config window_border_width 6
yabai -m config active_window_border_color 0xffbde270
yabai -m config normal_window_border_color 0xff555555
yabai -m config insert_feedback_color 0xffd75f5f
yabai -m config split_ratio 0.50
yabai -m config auto_balance on
yabai -m config mouse_modifier ctrl
yabai -m config mouse_action1 resize
yabai -m config mouse_action2 move
yabai -m config mouse_drop_action swap
. ~/.config/yabai/set-layout-based-on-display
yabai -m config top_padding 10
yabai -m config bottom_padding 10
yabai -m config left_padding 10
yabai -m config right_padding 10
yabai -m config window_gap 10

# bb ~/.config/yabai/rules.clj
# . ~/.config/yabai/layout
. ~/.config/yabai/signals

# yabai -m query --windows  | jq '.[] | select(.app == "Emacs") | .id'
echo "yabai configuration loaded.."
