#!/usr/bin/env bash

############## BAR ##############
sketchybar -m --bar height=25 \
	blur_radius=50 \
	position=top \
	padding_left=10 \
	padding_right=10 \
	color=0x44000000

############## GLOBAL DEFAULTS ##############
sketchybar -m --default updates=when_shown \
	drawing=on \
	cache_scripts=on \
	icon.font="PragmataPro:Bold:16.0" \
	icon.color=0xffffffff \
	label.font="PragmataPro:Bold:16.0" \
	label.color=0xffffffff

############## SPACE DEFAULTS ##############
sketchybar -m --default label.padding_left=2 \
	label.padding_right=2 \
	icon.padding_left=8 \
	label.padding_right=8

############## PRIMARY DISPLAY SPACES ##############
sketchybar -m --add space code left \
	--set code associated_space=1 \
	associated_display=1 \
	icon.font="PragmataPro:Bold:20.0" \
	icon= \
	icon.padding_right=3 \
	icon.highlight_color=0xff48aa2a \
	label=code \
	click_script="yabai -m space --focus 1" \
	\
	--add space coffee left \
	--set coffee associated_display=1 \
	associated_space=2 \
	icon.highlight_color=0xfffab402 \
	icon.font="PragmataPro:Bold:16.0" \
	icon= \
	label=coffee \
	click_script="yabai -m space --focus 2"

############## SECONDARY DISPLAY SPACES ##############
sketchybar -m --add space misc left \
	--set misc associated_display=2 \
	associated_space=5 \
	icon.font="PragmataPro:Bold:20.0" \
	icon= \
	icon.highlight_color=0xff48aa2a \
	icon.padding_right=3 \
	icon.padding_left=0 \
	label=misc \
	click_script="yabai -m space --focus 5"

############## ITEM DEFAULTS ###############
sketchybar -m --default label.padding_left=2 \
	icon.padding_right=2 \
	icon.padding_left=6 \
	label.padding_right=6

############## LEFT ITEMS ##############
sketchybar -m --add item space_separator left \
	--set space_separator icon= \
	associated_space=1 \
	associated_space=3 \
	icon.padding_left=15 \
	label.padding_right=15 \
	icon.font="PragmataPro:Bold:16.0" \
	\
	--add item githubIndicator left \
	--set githubIndicator associated_space=1 \
	update_freq=1000 \
	icon.font="PragmataPro:Bold:16.0" \
	icon= \
	click_script="open https://github.com" \
	script="~/.config/sketchybar/plugins/githubIndicator.sh" \
	--subscribe githubIndicator system_woke \
	\
	--add item topmem left \
	--set topmem associated_space=1 \
	icon.padding_left=0 \
	update_freq=15 \
	script="~/.config/sketchybar/plugins/topmem.sh"

############## RIGHT ITEMS ##############
sketchybar -m --add item battery right \
	--set battery \
	update_freq=20 \
	script="~/.config/sketchybar/plugins/power.sh" \
	label.font="Hack Nerd Font:Bold:16.0" \
	icon.font=":Bold:16.0"

sketchybar -m --add item clock right \
	--set clock update_freq=10 \
	script="~/.config/sketchybar/plugins/clock.sh" \
	\
	--add item mailIndicator right \
	--set mailIndicator associated_space=1,2,3 \
	update_freq=30 \
	script="~/.config/sketchybar/plugins/mailIndicator.sh" \
	icon.font="PragmataPro:Bold:16.0" \
	icon= \
	label.padding_right=-2 \
	click_script="hs -A -n -q -t 0.1 -c 'hs.application.launchOrFocus(\"Mail\")'"

# Creating Graphs
sketchybar -m \
	--add item topproc left \
	--set topproc associated_space=1 \
	icon.padding_left=0 \
	update_freq=15 \
	script="~/.config/sketchybar/plugins/topproc.sh" # \
# \
# --add graph cpu_user right 30 \
# --set cpu_user graph.color=0xffffffff \
# update_freq=2 \
# width=0 \
# associated_space=1 \
# label.padding_left=0 \
# script="~/.config/sketchybar/plugins/cpu_graph.sh" \
# lazy=on \
# \
# --add graph cpu_sys right 30 \
# --set cpu_sys label.padding_left=0 \
# associated_space=1 \
# graph.color=0xff48aa2a

# Stats
sketchybar -m --query default_menu_items | grep 'Stats;'
if (($? == 0)); then
	sketchybar -m --add alias Stats,'CPU_Line chart' right \
		--set Stats,'CPU_Line chart' \
		associated_space=1 \
		update_freq=5 \
		icon.padding_left=-2 \
		label.padding_right=-10

	sketchybar -m --add alias Stats,'RAM_Line chart' right \
		--set Stats,'RAM_Line chart' \
		associated_space=1 \
		update_freq=5 \
		icon.padding_left=-2 \
		label.padding_right=0
fi

# iStat Menus Status
sketchybar -m --query default_menu_items | grep 'iStat Menus Status;'
if (($? == 0)); then
	sketchybar -m --add alias 'iStat Menus Status',com.bjango.istatmenus.cpu right \
		--set 'iStat Menus Status',com.bjango.istatmenus.cpu \
		associated_space=1 \
		update_freq=5 \
		icon.padding_left=0 \
		label.padding_right=-5

	sketchybar -m --add alias 'iStat Menus Status',com.bjango.istatmenus.memory right \
		--set 'iStat Menus Status',com.bjango.istatmenus.memory \
		associated_space=1 \
		update_freq=5 \
		icon.padding_left=0 \
		label.padding_right=-5
fi

###################### CENTER ITEMS ###################

# Adding custom events which can listen on distributed notifications from other running processes
# sketchybar -m --add event spotify_change "com.spotify.client.PlaybackStateChanged"										\
#               --add item spotifyIndicator center                                                                          \
#               --set spotifyIndicator script="~/.config/sketchybar/plugins/spotifyIndicator.sh"                            \
#               --set spotifyIndicator click_script="osascript -e 'tell application                  \"Spotify\" to pause'" \
#               --subscribe spotifyIndicator spotify_change

############## FINALIZING THE SETUP ##############
sketchybar -m --update

echo "sketchybar configuration loaded.."

# brew install --cask stats
#       
