name: "system build"
on:
  push:
    branches:
      - master
  pull_request_target:
    branches:
      - master

concurrency:
  group: ${{ github.head_ref }}-builds
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          # - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          # Shallow clones won't work
          fetch-depth: 0
      - uses: cachix/install-nix-action@v22
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          extra_nix_config: |
            experimental-features = nix-command flakes
      - uses: cachix/cachix-action@v12
        with:
          name: rashawn
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          extraPullNames: nix-community
      - name: Run Flake Checks
        run: |
          nix flake check -v --show-trace
        timeout-minutes: 240
