notmuch-config: ENC[AES256_GCM,data:HFQMTf7nqn/sgAtpPu7Mih9+RrGMlMPi+GOIIg1XQ4bk0pFzfSVntF9e6Sia47R6H0jneVSNtKO4Uz61KnWBXwRwu+mbrZLpmVPpQvchHFgssZOkV+yKVQEJ2PwiJK6Y2QuOwCMui8U8cbRIi+TRlXH/U1cWAUk0HMwUO30K98lUiArOh+27TJNNHMw63tJorGNCyqfifZIrkXSSVwPeb5x3V5Bx6ESToi/jRNNZ2addiMzFdKBAiIVCfzopF0A9sYkdGWZJKoyiZtF0iiBCQbwkWoB5aDnVtx9j6GueRFHX38XtW9QfQagMjIQfNvdHIYh2vegMbGC2RPQGj9uwYaGMQZnF86DWgB3yt9dswD1R92BStZ5ugGPLiIE9rQVh4/9n/GR7D5AP2iGSVWH6H6mRhcAhHSr4WMkLdQexVjwlmCXVVDd6qlKM6VvL9ypWLEhUjjxoyXuOdrVeiIVj0tlfc1VYOUZDRQOdotxCKMguTGVY6JhJ4mvvYqNG+XarbZDpJI0qVbTlbxEIJa4H8xfdwk4elTkCQEpDDdwtkJsCKV+gyaVPs+tJN2TPNrFbflQq7s1D2BVtAWqoK1E7EpulAdlUt2Xd1ydJRv+eBJYAaMYgkvQwfJsv4hT7uAjjuLvAhaS6XUM97YyvKe5jRDrHqsYybVow4tfQKETN8qisZH6Z+6EU6h2yAxi1h3yYba+A1dQdD6PFcuC42jr5qWrVUr22TH6KxYT6rpWLdRQBPITVlOPBuMtHlMCRd9QF/cUjgEvkd2SSwHEwi6zbvGkO8PUKSo4UhUW7L81QHXqy+RfSnrSGMO2wUnKGioAExbS0EiiRniIxNqqkIZcuWLMJfQpDhRE/WImABpjqSjrIJkSCWBvh87SDus2AwtCsK9gRg2biaxUUUngCHb4b5MzON9V0OZJTgGdIxC6sIGBFLxODy27UVMLfAukHMkcvRA9fDS4a7IBgfXA2EBTGFD+P1+whnSddCgM980MR6nl7vMeaLAzAQNn9Ru/YYXAmH6AR+QZ2u6e7q++LGbe6grKaUkDv7PhOPddjmCjfHRpsEcIvqANOLmijQVGJswTb1FdNGXsa97isOo2fr/XyaqK6xoDV4SB6wb5Myo9+PAUsisyd2dWFQye6+et4BORbyUJV0yR8hs+PbtzZAqHX2oP7OdzPG1rcG7W56ch/Pl1lAwI6bbNLSz1uMFxCKpPZbw+q6gMxRjEU7LNcJHDA4ZuYF89rscSyAbWpO/Sutn8buWD58DlAmUedjZA68Ir9lkcBrAD3AOwCz5J88q0PhxEFWgMmzEuImN54bdtwi0ahG1MXqB5siGSKkbDUixA/e9+WvOh+BejpU/EovaOcWF7L+0fe9k6tzetkpR6CvM+BUVbi9rdRAT5pzJ7O6yxlpu7nHlLlw77pUI1rVbBcVEbJf2yk56UlUN8fOQo7Pn60Cyp+7Fmkfb1msw32UaeWNRomGz08iS+YP7PLyk8OTc1Q6V2C2gh45CIZ5ZoPQGPakYrfljos7KdfOpNtOEuoK7NShDkNYaAY5fXJ/yorMnbKNE3Xd5FeL4PEWgxvp9HiDiPwx0Vq+LtbZkkw61m96y4IjC9lKVrFsIVihJMB84cm/Ado6RYmEAUQhCJx/4qIUrnaqr+DMqZzlnTMvtSVt0ZUOATI/qKHffsQn3q9l7mlWDjqZf+Ci72LGE60tMB2pqmmZn86UHq71JlJDHm7IuTfj5nYUhhkpPD7kQFSq5vnoG9gDvprEepdVTSoZ1QEGmsKw5n22M3WMK4r3sxbLyxMNLOLbk1zwJCYpO4pduUnK37p2kEbwnE6Bdv0IU3/h+h8zFMsLFEQDzUfuz516/azcd8DdAcfM1pQwnN3cD+3AbV5bI+06IRXRfNJLqMJTPa/hKnQ66V+R4hZ53/HdOAuzHdHKKLXypFPSBQPV4rNoK1hfIYi7S+ztFvKe6LAwy5cMpy+vkLgCQOx2Gg/2Y/+uKUSRrQan8yXk9d5GS8WuzqekXez8tc9B4jN1e2+ekoHlT8NswZyD2jlt/rd9wpy0aR9+1elXz3t4+I+VuwhQowUyL5E3z3mVdglhKYFsX3ht7shJJaZWx/Rgy7SZHM42YHxJG/cRSQPLIU6gISz5F/5GXjExQuLyzMBnCrVTUoVsoiueBceoQpPwNrjVfYxcQcKag8Q4sqEWEcuEZO3F5bBJ+l6j50i6DBTQ6ECT4PekNsGUpwzalp5ONM38mEoo8T352JXCnjzf7KWgt7It23o60+KWmbZoLHHE8ylq5xiPy1+vgC7v01OQO7Wuvsqmdlz5UZQpvh2KVy9mUORa53lDicfr+j4dkL/M2kfnIzFSbnyE072z9vWrLICURlvSsV6Gw7iF/B7uBm/Da8XS7I2gSVKXxZYv1IOTy/UizjcPoSyOX2BZhfBGluP+ySU+colCSUYru7bJJOiDx53Iz9+ah2aA3v0JYFrbLHMJao3f1PyNJVIyUpF9B+JCSDIVtB0vltgYt4NwYXQHKFde+vCFwBDCy1qw4l4aeIfEt6iX0joVc9AxKvrgQaJU4V/wwYXK4t3MOWfcEe4Gpvy3A+84rXQmXUZJvfX5gQbHsxIvneRPXa+Jqr7uN1IbAtEiz2fZKrWOCWW3KKUJpCRP7xrNyxpDVorPxwnI+DsmwQOgrnTWpHjkzCjKDEI0C3r0puAoegJuNwoeiLAJK8czK9X12V61s2/HBazfGUrfyMbcCSQZBQD678mN6kbf3ixeCG4MpqpZdo0+wvNDvNVrKJaOp4a/2yX8gkte3+whTtQ5RjbRuG0olemlD7SKPEqwelbNPwiJSscN4GTF8AF0IbrgBNfyClE7yavAUKOSNH0Lc2YBLzTfxHeGUGw24ikY2Flgd1VhOXQxcVEHOk9cibG5nQrVU1sNao6mOJ3nj/lxF11RksMmPpLIbhyKDtppkAGMFOhJhH/cJDeOgXaFWjcmVm06kaTZxSqON5rbJKlr7BH0/GSFpK4QRQ4EIXwNSVGc/8rAVXQujAn0Cpo3Vm4/V5ICV4P3+hULGS67MSZJLkvv6iQ87Lh5kETU4SrGvDWmvGT3Obda210Dmwh4M2iUSZd2DT0zyIQFlgE+mMupKVBrCES42SINAhPBYmgAt7Tu8jlKC6MrNaIjsFSao+8+q77qkD3AJ8yxsUw8mIOffZNuz6Cgk8NZVKAR1XFBnzmaZ+u6eR7Osr6AUzR8OJ0izA6HekWhrVPSQMlNGZyT1+zXzaa8wzxs60xmHXFT3/H6GkuNa4FzKsl4qATdMRqpKlkhLB/SOq41LES1Dh5ev+H11SZvpW6yjfPb2jlX6jmdctSqoGAHowdU5DLCTqJdLYFWQER/fHRCjfkUNAmZs3ZJF2N9dDVqQtellxEgzo2jhxTJvMTGAo8n4rVH45SBqEBEDTqCVXvWvia1VHnlRcUUNBGMNyOrWEqXNRitvZA0r8muiJGIePPFmtB3vkQroqo4asH6XCb1skgXkozMSjFFNHNFfzhH6JYOeZXyFVUF2jOsJ0bVc6Z+O2ejQ93t/a8fLoqcIvet5b7StXSN1Kx00R1xkSAUymxdZW3MFGExE300eURC7c6n0cKjxCsyVyBAVi0n/VJ/STbMwnN619sqvtL/wS0MZhDNV4plez+NI14jrYdVaCHGQtjgDiPi2f8l04iDgw=,iv:2otWqid1GovoeIg/b4+2787xBs9+SepOs+U7qh/GkMI=,tag:82S4CMhRjOhHeBEue2eVvw==,type:str]
sops:
    age:
        - recipient: age1k2punqk6m96wlr7dxcx5255dcse30rr8gcpqrqhejre2v2ggfygq0hfqzt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwMUVkcGhrMlhMZHAvSlYz
            THNKeDgxYUxqTTJqQ1NvUGx5NEdyNWtVQmw4CmUzVHpzL3B0THR0MTRwb3dMMUF3
            Z3h5Ym16UUpiUC9Zc0s4cy8yNFRueFEKLS0tIGtBeDJCc2JxUzJsU0g0ckZqRzBz
            R2xSSi9oTllCYUU2cUZYUmZsUk03emcK0997rR+6TrYJmjhUKnfWAxlf+3shp3nM
            p8pJ/ANU6YMOdDn4a8MmXbULZ61ApwFURCCXdZOuSI6D5DuK7p9oJA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1479up9vpv9cqxf82m9nmrj2dlkzm5vjg69hms3pu525ttucaksaq980qpx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4bXZneEFDMUJyU1BsQSs0
            SUlqUVlEL0VNV0JhOVU1REJzN0xta0NOWDBBCm8yQ2RzMy82djdSS042Mkp2NHZU
            SDljZWZlR291RnZMVzNlYmlUWTBlaWsKLS0tIE8rbGJJUHlweVN2dDBIZjNCWWRG
            TWJWTHZrTWhRK2ExWDBmWEtqSVAzV00KxOUxReXZtziN3Wft2ihyX//0bIaSqARB
            SNHwnufexHgGFXFUqA6btMonTS458sZeLF67gNOp6VbDszUwtSz08Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1957d6rczw7q2k2zzjqvql02t90wzw0lakqqw9252w9jqnc88mpxqc849ya
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCOFhUbGZVWitHejBXRXZ5
            b0ptdmFMVFlkdjRicW84bkJkOU1hZUIvQlVjCm1tT2dVNHFNMCtPZDIvUk82N0tX
            cm5MYVdQTlRkdGJwblpSR25sd04ydzgKLS0tIFBvakU0YjFSbjlpM2tPRVVJMmk1
            a2dPMThMV2g4Mmh2dFExR2NLT1MwUVUKb6qnP85pFzg6PZZG/2XlSbqCLCRdH8py
            BlEWCid+/kHvDEEcDiCVjTklz+JWMqqIsU5c2P18jMhIk4X9q47LPg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age128kvdhfwkeqdhjdp25pnlj97rr3egacm98c3vllm90zs90tfnqrq5kmeh6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKOHcxczZRbSs0QkhvdUx5
            RzdsUUFtOENHa1FHUkxnOW9SQk5FU3V4UHhZCmVVRGMweTh4UGoxYUh4RlpkSFhq
            SWtvVGN0VEEvOFNJcFhacDZlWExqLzAKLS0tIEZzS3pGRUpFeGZuU1Vxb0VUSURu
            MWp0WmxNMFA3cURmdkFOTTF0S1U4azgKDj5NY9aHwxdUnhl2QvH7Vu9kMwHVFMxP
            iLP5iYZFaFrPJzQGw2fJNb5QwWVzY0mF57YZKLYqd0kKgTZhdrtBWA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-14T07:37:41Z"
    mac: ENC[AES256_GCM,data:2YNQymtg46RND1lPFcpM3Mq84hpcr3wJVGCcouW1w/PNZhchc48MgUAYGyK9tj+hACAvgwzsS4VFk2CBSG9XbtccR4GPLI/0NcDddC2g7wlbEtewMZRNwLu+01Zv9oLH2KtEvvefFy7qt/JhQe55ez0SdzAcNT+rQzGGPR7fIyw=,iv:xVGwO/KCUad9varnoZPl/C0Ln7z/a6patjmwtFmzpIM=,tag:UTyyreKHLolkCuI4BYJGcw==,type:str]
    pgp:
        - created_at: "2026-03-14T07:37:41Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA9X2pQo2ALtXAQ/+K8m9qc8zpABSwBonKrMujlTy9Luil4roScfdXj8Dj478
            Kzj400BNZqEpfBeRYckP8IWiVYGH77XytQE1IBZfybfg9e8Ml4PKR1btoFNq6o64
            jv4l6938fsrfM2T0wd2ci8OI56EhDf5fftLsdebAz3OnMmC3/7sh5Rl0A8FtILKd
            Ae4NYr9uPIzGrF+QA7lFLULJMXEzTYfL0lcNYAR9kQd6yBfpetG8DaCQl0qGrRWu
            7KYWnSSq9+FpFHxgTlkeuSMMuXaZga9n51C0FzQnLXBknRXqZjb8ARrRdyvVKU5K
            3Y8nbwbDDGu/LPfE8M/H0+yfXbStQJugZX+djGG40xaWv48ctjBRgmccHyWzmZ4q
            7FZ3lD2yzIBzsK2lcCtixlVxrKYly7dbH6YcsgbMrwSzExDVUWGrvEPnrpOeq5Ii
            VH34gCI0uP/FjqKuGgbdkldqUyc5zqLJXq6LfsiyJJxzC3LXrVUL3788ZZCSATO7
            IJw8dJS7fhkMo86cIFtbfNJPOolJevmA+D+2lFpT023c0Q+DH6QaUH+R/B/6w+5v
            63EKLAohhZA00WxsVITR8qNTAa/R180iRHfv2pyjFOHtpwr+h5mOxGjE4aZj+tql
            uD79UUaMEvYr8ZF/gvyEzGvXkuLye5nrolAlNuAb7CI6gcC90PgdEwMKe+NbLdfS
            XgG60E2PUGFgwXVvbIuT19UfdUlqQvlaPJ+wreBAE793QX6vSmEX5+QOpjbUu5XQ
            Fd7ZiMZgp5hxoEyAx8b4vRNSGIukGLGDEMSsWKHpkXv1vGKXhbaiUTL4oZA0ccM=
            =gtuL
            -----END PGP MESSAGE-----
          fp: B198FB15EC5C13012E940B37E394C5D9A8E535A6
    unencrypted_suffix: _unencrypted
    version: 3.11.0
